swagger: "2.0"
info:
  version: "1.0.0"
  title: Miataru
  description: The Miataru API is very simple and straight forward. Generally you're posting (HTTP POST) a JSON formatted request to a service method locations and you get back a JSON formatted answer. Please take into consideration that this has the request-for-comment status and that it can change while there's work done on client and server applications. Versioning therefore is done by prepending the version number - /v1/ for version 1 - to the method call.
  contact:
    name: Miataru Team
    email: info@miataru.com
    url: http://miataru.com
  license:
    name: Public Domain
    url: https://raw.githubusercontent.com/miataru/miataru-protocol-specification/master/LICENSE
# during dev, should point to your local machine
host: service.miataru.com
basePath: /v1
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /UpdateLocation:
   post:
    tags:
      - updateLocation
    description: This method is used to update the location of a device. The device does not need to be known already to the Miataru server but it rather creates a unique identifier for itself in the client application. This unique identifier, or device ID is then used to address this particular device.
    operationId: updateLocation
    produces:
      - application/json
    parameters:
      - name: body
        in: body
        description: the body of this UpdateLocation POST request contains the JSON formatted parameters.
        required: true
        schema:
          $ref: '#/definitions/MiataruUpdateLocationRequest'
    responses:
      default:
        description: successful request
        schema:
          $ref: '#/definitions/ACK'
  /GetLocation:
    post:
      tags:
      - getLocation
      description: To retrieve a specific devices latest known location the /GetLocation method is used. Please note that the MiataruConfig portion is optional. RequestMiataruDeviceID should be the ID of the device the request is sent from (or an identifier like an URL).
      operationId: getLocation
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: the complex JSON formatted datastructure to get the location of one or more devices.
          required: true
          schema:
            $ref: '#/definitions/MiataruGetLocationRequest'
      responses:
        default:
          description: successful location responses
          schema:
            $ref: '#/definitions/MiataruGetLocationResponse'
  /GetLocationGeoJSON/{deviceID}:
    get:
      tags:
      - getLocation
      description: Retrieves a devices Location in GeoJSON format.
      operationId: getLocationGeoJSON
      produces:
        - application/json
      parameters:
        - name: deviceID
          in: path
          type: string
          required: true
          description: the unique device ID of the device the location is requested from
          default: "7b8e6e0ee5296db345162dc2ef652c1350761823"
      responses:
        default:
          description: geoJSON formatted device location
          schema:
            $ref: '#/definitions/MiataruGetLocationGeoJSONResponse'
  /GetLocationHistory:
    post:
      tags:
      - getLocation
      description: Location History is stored on the server only if the client told the server to do so using the “EnableLocationHistory” setting in the Location Update requests. For transitions of enabling/disabling that functionality - Everytime a Location Update is received by the server with “EnableLocationHistory=false” the server removes all stored Location History till that point. There is a server-side setting that controls up to how many Location Updates the server is storing in the Location History before it removes the oldest one. To request the Location History of a particular device the client sends the following POST request to the GetLocationHistory service URL. Please note that the MiataruConfig portion is optional. RequestMiataruDeviceID should be the ID of the device the request is sent from (or an identifier like an URL).
      operationId: getLocationHistory
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: the complex JSON formatted datastructure to get the location history of one device
          required: true
          schema: 
            $ref: '#/definitions/MiataruGetLocationHistoryRequest'
      responses:
        default:
          description: successful location history response
          schema:
            $ref: '#/definitions/MiataruGetLocationHistoryResponse'
  /GetVisitorHistory:
    post:
      tags:
      - getVisitorHistory
      description: Visitor History is stored on the server with every request to the location or location history information of a device. There is a server-side setting that controls up to how many Visitors the server is storing in the Visitor History before it removes the oldest one. To request the Visitor History of a particular device the client sends the following POST request to the GetVisitorHistory service URL.
      operationId: getVisitorHistory
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: the complex JSON formatted datastructure to get the visitor history of one device
          required: true
          schema:
            $ref: '#/definitions/MiataruGetVisitorHistoryRequest'
      responses:
        default:
          description: visitor history response
          schema:
            $ref: '#/definitions/MiataruGetVisitorHistoryResponse'

# complex objects have schema definitions
definitions:
  MiataruVisitors:
    required:
      - DeviceID
      - TimeStamp
    properties:
      DeviceID:
        type: string
        description: the device id of the visiting device. If this is an empty string the deviceID is unknown/was not reported.
      TimeStamp:
        type: string
        description: the javascript timestamp of the visit
  MiataruGetVisitorHistoryRequest:
    required:
      - MiataruGetVisitorHistory
    properties:
      MiataruGetVisitorHistory:
        type: object
        required:
          - Device
          - Amount
        properties:
          Device:
            type: string
            description: the device id of which the visitor history is requested
            default: "7b8e6e0ee5296db345162dc2ef652c1350761823"
          Amount:
            type: string
            description: the maximum number of visitor history entries to be retrieved
            default: "10"
  MiataruGetVisitorHistoryResponse:
    required:
      - MiataruServerConfig
      - MiataruVisitors
    properties:
      MiataruServerConfig:
        type: object
        description: holds information about the server side settings of the visitor history and about the available device related visitor history.
        required:
          - MaximumNumberOfVisitorHistory
          - AvailableVisitorHistory
        properties:
          MaximumNumberOfVisitorHistory:
            type: string
            description: a server-side setting that controls up to how many Visitors the server is storing in the Visitor History before it removes the oldest one.
          AvailableVisitorHistory:
            type: string
            description: the number of available visitor history entries for this device. If the client requested more Visitor Updates than there are available the server will return those available.
      MiataruVisitors:
        type: array
        description: The server will answer back with an Array of MiataruVisitors if there are Visitors, or an empty array when there are none.
        items:
          $ref: '#/definitions/MiataruVisitors'
  MiataruGetLocationHistoryResponse:
    required:
      - MiataruServerConfig
      - MiataruLocation
    properties:
      MiataruServerConfig:
        type: object
        description: holds information about the basic configuration settings on server side.
        required:
          - MaximumNumberOfLocationUpdates
          - AvailableDeviceLocationUpdates
        properties:
          MaximumNumberOfLocationUpdates:
            type: string
            description: the amount of locations the server is storing per device at maximum before it will remove the oldest one (FiFo)
          AvailableDeviceLocationUpdates:
            type: string
            description: the number of locations stored for this particular device
      MiataruLocation:
        type: array
        description: holds all location information of a given device or is an empty array if device not found or no location information is stored.
        items:
          $ref: '#/definitions/MiataruLocation'
  MiataruGetLocationHistoryRequest:
    required:
      - MiataruGetLocationHistory
    properties:
      MiataruConfig:
        type: object
        description: the configuration for this request. please note that it's optional.
        required:
          - RequestMiataruDeviceID
        properties:
          RequestMiataruDeviceID:
            type: string
            description:  RequestMiataruDeviceID should be the ID of the device the request is sent from (or an identifier like an URL).
            default: "6140c3c0-4a7d-40d2-99ab-39414cac3509"
      MiataruGetLocationHistory:
        type: object
        description: one device id for which the location history should be retrieved.
        required:
          - Device
          - Amount
        properties:
          Device:
            type: string
            description: the device id of which the location history shall be requested
            default: "7b8e6e0ee5296db345162dc2ef652c1350761823"
          Amount:
            type: string
            description: the maximum number of location history entries that are requested.
            default: "10"
  MiataruGetLocationDevice:
    type: object
    required:
      - Device
    properties:
      Device:
        type: string
        description: the unique device id of a device.
        default: "7b8e6e0ee5296db345162dc2ef652c1350761823"
  MiataruGetLocationRequest:
    required:
      - MiataruGetLocation
    properties:
      MiataruConfig:
        type: object
        description: the configuration for this request. please note that it's optional.
        required:
          - RequestMiataruDeviceID
        properties:
          RequestMiataruDeviceID:
            type: string
            description:  RequestMiataruDeviceID should be the ID of the device the request is sent from (or an identifier like an URL).
            default: "6140c3c0-4a7d-40d2-99ab-39414cac3509"
      MiataruGetLocation:
        type: array
        description: one or more devices in an array for which the location should be retrieved.
        items: 
          $ref: '#/definitions/MiataruGetLocationDevice'
  MiataruLocation:
    type: object
    required:
      - Device
      - Timestamp
      - Longitude
      - Latitude
      - HorizontalAccuracy
    properties:
      Device:
        type: string
        description: the unique id of this device. This needs to be unique as it is the only piece of information directly pointing towards this one device. Generating a GUID per device is recommended.
        default: "7b8e6e0ee5296db345162dc2ef652c1350761823"
      Timestamp:
        type: string
        description: the javascript timestamp of this location update
        default: "1441360863"
      Longitude:
        type: string
        description: longitude of the position that is reported
        default: "-4.394531"
      Latitude:
        type: string
        description: latitude of the position that is reported
        default: "41.079351"
      HorizontalAccuracy:
        type: string
        description: the accuracy of this location update in meters
        default: "50"
  MiataruGetLocationGeoJSONResponse:
    type: object
    required:
      - geometry
      - type
      - properties
    properties:
      geometry:
        type: object
        required:
          - type
          - coordinates
        properties:
          type:
            type: string
          coordinates:
            type: array
            items:
              type: number
              format: float
      type:
        type: string
      properties:
        type: object
        required:
          - name
        properties:
          name:
            type: string
  MiataruGetLocationResponse:
    type: object
    required:
      - MiataruLocation
    properties:
      MiataruLocation:
        type: array
        items: 
          $ref: '#/definitions/MiataruLocation'
  MiataruUpdateLocationRequest:
    required:
      - MiataruConfig
      - MiataruLocation
    properties:
      MiataruConfig:
        type: object
        description: the configuration for this request.
        required:
          - EnableLocationHistory
          - LocationDataRetentionTime
        properties:
          EnableLocationHistory:
            type: string
            description: If the client tells the server to store a location history the server automatically disables the pre-configured data time-out behavior that removes location data after a given amount of time. Nevertheless the user is limited to the server-side pre-configured amount of location history entries. This is either True or False.
            default: "False"
          LocationDataRetentionTime:
            type: string
            default: "30"
            description: The LocationDataRetentionTime is the amount of minutes the server will keep that Location Data before it is removed/deleted automatically.
      MiataruLocation:
        type: array
        items:
          $ref: '#/definitions/MiataruLocation'
  ACK:
    required:
      - MiataruResponse
      - MiataruVerboseResponse
    properties:
      MiataruResponse:
        type: string
        default: "ACK"
      MiataruVerboseResponse:
        type: string