name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme CodeScanner
    - name: Build ( iOS)
      run: xcodebuild build -scheme CodeScanner -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16 Pro'
    - name: Build ( visionOS)
      run: xcodebuild build -scheme CodeScanner -destination 'platform=visionOS Simulator,OS=latest,name=Apple Vision Pro'
    - name: Build ( mac Catalyst)
      run: xcodebuild build -scheme CodeScanner -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst'
