name: Darwin

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build SPM
      run: swift build
    - name: Test SPM
      run: swift test
    - name: Lint Podspec
      run: pod lib lint --allow-warnings --use-libraries
